version: '3'
services:
  db:
    image: mysql:5.7
    env_file:
      - dev.env
    command: --init-file /data/application/init.sql  
    volumes:
       - .\init.sql:/data/application/init.sql
       #- .\data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db 
    env_file:
      - dev.env
    ports:
      - 8080:80
  swagger:
    image: swaggerapi/swagger-ui
    environment:
        API_URL: openapi.yaml
    ports:
      - 8000:8080
    volumes:
      - .\openapi.yaml:/usr/share/nginx/html/openapi.yaml
  app:
    image: webdevops/php-nginx:8.2-alpine
    depends_on:
      - db 
    env_file:
      - dev.env
    ports:
      - 5000:80
    volumes:
      - .\app:/app