version: '3'

volumes:
  db_data:
  
services:
  db:
    image: mysql:5.7
    env_file:
      - dev.env
    command: --init-file /data/application/init.sql  
    volumes:
       - .\Test.sql:/data/application/init.sql
       - db_data:/var/lib/mysql  
       
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db 
    env_file:
      - dev.env
    ports:
      - 8000:80
      
  swagger:
    image: swaggerapi/swagger-ui
    environment:
        API_URL: openapi.yaml
    ports:
      - 8080:8080
    volumes:
      - .\openapi.yaml:/usr/share/nginx/html/openapi.yaml
      
  app:
    image: webdevops/php-nginx:8.2-alpine
    depends_on:
      - db 
    env_file:
      - dev.env
    ports:
      - 443:443
    volumes:
      - .\app:/app
      - .\cors.conf:/opt/docker/etc/nginx/vhost.common.d/01-cors.conf
