openapi: 3.0.0
info:
  version: 1.0.0
  title: User API
servers:
  - url: https://localhost
components:
  securitySchemes:
    basicAuth:  
      type: http
      scheme: basic
paths:
  /users:
    get:
      summary: Get list of users
      operationId: getUsers
      security:
        - basicAuth: [] 
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
    post:
      summary: Create user
      operationId: createUser
      security:
        - basicAuth: [] 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/text:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /users?id={id}:

    get:
      summary: Get user by ID
      operationId: getUser
      security:
        - basicAuth: [] 
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
    put:
      summary: Update user
      operationId: updateUser
      security:
        - basicAuth: [] 
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/text:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete user
      operationId: deleteUser
      security:
        - basicAuth: [] 
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/text:
              schema:
                type: object
                properties:
                  message:
                    type: string
